### ISSUE TITLE
Get estimates

### ISSUE THREAD

**Issue by afred** [afred/move#15]
use [this spreadsheet](https://docs.google.com/spreadsheets/d/1sbeLoy4aKsxttkER-fGXY-bAXeT5VVkwZZAeqVkq1nI/edit?usp=sharing)

**done when** we have estimates from
- [x] upack
- [x] door to door
- [ ] pods
- [ ]  uhaul
- [ ] others

**Comment by tshrum** [comment]
done, went with packrat for $2,800.

**Comment by tshrum** [comment]
see #3 for order details from PackRat
