### ISSUE TITLE
Appraise cello

### ISSUE THREAD

**Issue by afred** [afred/move#18]
**done when** we have an appraisal for the cello that can be used to add it to insurance policy.

**Comment by afred** [comment]
@tshrum so what was the final value, and what do we do with it?

**Comment by tshrum** [comment]
@afred I will pick up the cello tomorrow with the paperwork. Then I'll submit a scheduled item to our renters policy.

**Comment by afred** [comment]
Got it. Cello appraisal docs last seen in @tshrum's purse. Next up, #34.
