### ISSUE TITLE
Renters Insurance

### ISSUE THREAD

**Issue by tshrum** [afred/move#22]
- [x] Call about coverage during the move
- [x] Change address for policy or cancel
- [ ] If needed, get a new policy for new place

**Comment by tshrum** [comment]
Once we have signed the lease, call for a quote:
American Family Insurance - Gina Rowsam
1823 Folsom St
(303) 444-8264

**Comment by afred** [comment]
@tshrum are we going AmFam in Colorado?

**Comment by tshrum** [comment]
@afred not necessarily. but my amfam bias makes me want to at least get a quote.

**Comment by tshrum** [comment]
@afred my dad is considering getting a license for colorado. in that case, we'll have to switch. :)

**Comment by tshrum** [comment]
@afred Amfam is competitively priced. We'll pay a few bucks more a month to have a real live person to deal with our bidniz. I will stop by their office tomorrow afternoon to make the switch.

**Comment by tshrum** [comment]
Renters and auto insurance acquired. Now we need to cancel the old auto policy. New ticket item.
