### ISSUE TITLE
Contact PackRat and confirm dates and give credit card for payment

### ISSUE THREAD

**Issue by tshrum** [afred/move#23]
**done when** dates and times have been confirmed for the following events.
- [x] Friday 6/17 - Drop off at Somerville apt
- [x] Saturday 6/18 after 1:30pm - Pickup loaded trailer from Somerville apt
- [x] Tuesday 7/5 - Container delivered to Boulder apt
- [x] Thursday 7/7 - Pick up empty  trailer in Boulder apt.

See #3 for PackRat order confirmation.

**Comment by afred** [comment]
@tshrum do they need a credit card to confirm our reservation?

**Comment by afred** [comment]
* Drop off at Somerville apt Friday 6/17
* Pickup loaded after 1:30 p.m. Saturday
* Guaranteeing delivery on 7/5
