### ISSUE TITLE
Finalize Move-In Date

### ISSUE THREAD

**Issue by tshrum** [afred/move#29]
Done when:
- [x] Contact Pennant to ask about possibility of early move-in
- [x] Pennant confirms the move-in date

**Comment by afred** [comment]
Contacted Pennant 6/10. Jessica Feldman said she has mentioned to the current tenant that we would be interested in an early move-in. She said she'll get an answer to us by Monday, 6/13.

**Comment by afred** [comment]
Contacted Pennant on 6/10. Jessica Feldman said she has mentioned to the current tenant that we would be interested in an early move-in. She said she'll get an answer to us by Monday, 6/13.

**Comment by afred** [comment]
We're going to go with July 1 for now. Our containers won't arrive until the 5th anyway, so early move in won't be advantageous. Never heard back from Jessica anyway. Closing.

**Comment by tshrum** [comment]
We upgraded to expedited shipping of the containers. The container is scheduled to arrive some time on the 29th. We will unpack it on the 30th and they will pick it up on July 1.

If we end up doing dinner with Wes and Bina in Salina, then we may opt to move the date back.
