### ISSUE TITLE
Get boxes

### ISSUE THREAD

**Issue by afred** [afred/move#32]
**Done when** we have roughly the right amount of boxes we'll need to pack everything.

**Comment by tshrum** [comment]
Got some boxes from Target! Need more.

**Comment by tshrum** [comment]
Got some more boxes. Driving around on trash days seems to be the best strategy. Do this tomorrow.

**Comment by tshrum** [comment]
Got 14 more sm, med, and lg boxes from MB. Should be enough. If not, they seem to have a pretty steady supply. Closing this.
