### ISSUE TITLE
Get parking passes for moving container

### ISSUE THREAD

**Issue by tshrum** [afred/move#33]
**done when**
- [x] signs are hung out front
- [x] 311 has been called
- [x] location of permit for trailer is noted below

**Comment by tshrum** [comment]
Parking passes acquired. Hang up signs and CALL 311 when signs are hung!

**Comment by afred** [comment]
If we need a tow, then call 617.666.3311, and refer to this confirmation number: 497439

@tshrum Note that I just set this up, and I missed the 48 hour window by a couple of hours. So they wouldn't be able to legally tow anybody until 2:20pm on 6/17, even though the sign says 12pm.

**Parking permit** is in my backpack
