### ISSUE TITLE
Take care of Comcast cable box

### ISSUE THREAD

**Issue by afred** [afred/move#36]
**done when** either cable box is returned, or we have confirmed that we can take it with us.

**Comment by afred** [comment]
We can stay with Xfinity for now, which makes things eaiser. Filled out their form online, expecting a call shortly...

![image](https://cloud.githubusercontent.com/assets/1507490/15915551/38ad0600-2db8-11e6-802e-eb056f0baf29.png)

**Comment by afred** [comment]
@tshrum did you ever get a call from Comcast the other night?

**Comment by afred** [comment]
@tshrum is this ready to close? And if so, can you please make a note of relevant dates and other info? Thanks!

**Comment by tshrum** [comment]
Transferred service.

New Acct #: 8497101003312393

Upon arrival, call activation department after the boxes are hooked up. 855-652-3446

**Comment by afred** [comment]
see #42 for follow up
