### ISSUE TITLE
Change address on major accounts

### ISSUE THREAD

**Issue by tshrum** [afred/move#54]
Done when addresses have been changed for:
- [ ] CSB
- [ ] AmFam
- [x] Amazon.com
- [x] Ebay/Paypal
- [ ] Capital One
- [ ] Chase
- [ ] American Express
- [ ] Discover
- [ ] Target?
- [ ] Student loans for Drew
- [ ] Student loans for Trisha
- [ ] Harvard?
- [ ] WGBH
- [ ] UC
- [ ] etrade

**Comment by afred** [comment]
Stale ticket. Closing.
